name: Deploy Website
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install MkDocs and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install mkdocs mkdocs-material pymdown-extensions
      
      - name: Build MkDocs documentation
        run: |
          cd site/projects/MQRdocs
          mkdocs build
          mkdir -p ../../../site/static/qtc-docs
          cp -r site/* ../../../site/static/qtc-docs/
      
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.4'
          cabal-version: '3.6'
      
      - name: Build Site
        run: |
          cabal update
          cabal build
          cabal run rokokot-site build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site